version: '3.4'

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./test-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime

