version: "3.8"

services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    hostname: oracle-db
    restart: always
    ports:
      - "1521:1521"
        #- "7080:8080" # Oracle Enterprise Manager HTTP port
    environment:
      ORACLE_SID: XE
      ORACLE_PWD: oracle
      ORACLE_USERNAME: system
      ORACLE_ALLOW_REMOTE: true
    volumes:
      - ./test-data:/oradata/orcl

volumes:
  oradata:
